
import clothes1 from './assets/clothes1.webp'
import clothes2 from './assets/clothes2.webp'
import clothes4 from './assets/clothes4.webp'
import clothes3 from './assets/clothes4.webp'
import AddIcCallIcon from '@mui/icons-material/AddIcCall';
import MenuOutlinedIcon from '@mui/icons-material/MenuOutlined';
import StoreOutlinedIcon from '@mui/icons-material/StoreOutlined';
import men1 from './assets/men1.webp'
import men2 from './assets/men2.webp'
import men3 from './assets/men3.webp'
import men4 from './assets/men4.webp'
import cup1 from './assets/couple1.webp'
import cup2 from './assets/couple2.webp'
import cup3 from './assets/couple3.webp'
import cup4 from './assets/couple4.webp'
import cup5 from './assets/couple5.webp'
import cup6 from './assets/couple6.webp'
import cup7 from './assets/couple7.webp'
import cup8 from './assets/couple8.webp'
import cup9 from './assets/couple9.webp'
import cup10 from './assets/couple10.webp'
import women1 from './assets/women1.webp'
import women2 from './assets/women2.webp'
import women3 from './assets/women3.webp'
import women4 from './assets/women4.webp'
import women5 from './assets/women5.webp'
import women6 from './assets/women6.webp'
import women7 from './assets/women7.webp'
import women8 from './assets/women8.webp'
import women9 from './assets/women9.webp'
import women10 from './assets/women10.webp'
import menformal1 from './assets/menformal1.webp'
import menformal2 from './assets/menformal2.webp'
import menformal3 from './assets/mensformal3.webp'
import menformal4 from './assets/mensformal8.webp'
import menformal5 from './assets/mensformal5.webp'
import menformal6 from './assets/mensformal6.webp'
import menformal7 from './assets/mensformal7.webp'
import menformal8 from './assets/mensformal8.webp'
import menformal9 from './assets/mensformal9.webp'
import MW1 from './assets/MW1.webp'
import MW2 from './assets/MW2.webp'
import MW3 from './assets/MW3.jpg'
import MW4 from './assets/MW4.webp'
import MW5 from './assets/MW5.webp'
import MW6 from './assets/MW6.webp'








export const megaMenuAllData = [
    {
        mainHead: "ALL",
        listData: [{title:"Men T-Shirts",id:1}, {title:"Men  Half Sleeve",id:7}, {title:"Men Full Sleeve",id:8}, {title:"Couple Collection",id:4}, {title:"Shop",id:5}],
        id:1
    },
    {
        mainHead: "MEN",
        listData: [{title:"Men Half Sleeve",id:7}, {title:"Men Full Sleeve",id:8},{title:"Formal Shirts",id:5},{title:"Men T-Shirts",id:1},{title:"Couple T-Shirt",id:4}],
        id:2
    },
    {
        mainHead: "WOMEN",
        listData: [{title:"Women Half Sleeve",id:2},{title:"Women Full Sleeve",id:3}, {title:"Men Women Collection",id:6},{title:"Couple Collection",id:4},{title:"Men T-Shirts",id:1}],
        id:3
    }
]


export const megaMenuClothesData = [
    {
        id:6,
        img: clothes1,
        title: "NEW ARRIVALS",
        magnifyImg: [clothes1,
            clothes1,
            clothes1,
            clothes1,],



    },
    {
        id:1,
        img: clothes2,
        title: "MEN",
        magnifyImg: [clothes1,
            clothes1,
            clothes1,
            clothes1,]

    },
    {
        id:2,
        img: clothes3,
        title: "WOMEN",
        magnifyImg: [clothes1,
            clothes1,
            clothes1,
            clothes1,]
    },
    {
        id:6,
        img: clothes4,
        title: "MEN-WOMEN",
        magnifyImg: [clothes1,
            clothes1,
            clothes1,
            clothes1,]
    }
]


export const megaMenuList = [
    {
        title: "ALL CATEGORIES",
        icon: <MenuOutlinedIcon sx={{ fontSize: "20px", mr: "5px" }} />,
        megaMenu: true,
        navigator: "allcategories"
    },
    {
        title: "SHOP",
        icon: <StoreOutlinedIcon sx={{ fontSize: "20px", mr: "5px" }} />,
        megaMenu: false,
        navigator: "shoppage/shop"
    },
    {
        title: "CLOTHES",
        icon: <StoreOutlinedIcon sx={{ fontSize: "20px", mr: "5px" }} />,
        megaMenu: true,
        navigator: "clothes"
    },
    {
        title: "CONTACT US",
        icon: <AddIcCallIcon sx={{ fontSize: "16px", mr: "5px" }} />,
        megaMenu: false,
        navigator: "contactus"
    }
]


const AllCat = [

    // Men T-shirt 

    {
        _id: 1,
        catName: "Men T-shirt",
        cat_Id: 1,
        productName: "4 THOUGHTS",
        isAvailable: true,
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
        sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        magnifyImg: [{img:menformal1},
            {img:menformal1},
            {img:menformal1},
            {img:menformal1},]
    },
    {
        _id: 2,
        catName: "Men T-shirt",
        cat_Id: 1,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" },{ title: "hello this is title", description: "hello this is description" }],
        productName: "ABSTRACT ELEMENT LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 799,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal2},
            {img:menformal2},
            {img:menformal2},
            {img:menformal2},]
    },
    {
        _id: 3,
        catName: "Men T-shirt",
        cat_Id: 1,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ALPHABET PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        isAvailable: true,
        magnifyImg: [{img:menformal3},
            {img:menformal3},
            {img:menformal3},
            {img:menformal3},]
    },
    {
        _id: 4,
        catName: "Men T-shirt",
        cat_Id: 1,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BLACK SMOKE OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal4},
            {img:menformal4},
            {img:menformal4},
            {img:menformal4},]
    },
    {
        _id: 5,
        catName: "Men T-shirt",
        cat_Id: 1,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BOLD BLACK PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal5},
            {img:menformal5},
            {img:menformal5},
            {img:menformal5},]
    },
    {
        _id: 6,
        catName: "Men T-shirt",
        cat_Id: 1,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal6},
            {img:menformal6},
            {img:menformal6},
            {img:menformal6},]
    },
    {
        _id: 7,
        catName: "Men T-shirt",
        cat_Id: 1,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal7},
            {img:menformal7},
            {img:menformal7},
            {img:menformal7},]
    },
    {
        _id: 8,
        catName: "Men T-shirt",
        cat_Id: 1,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal8},
            {img:menformal8},
            {img:menformal8},
            {img:menformal8},]

    },
    {
        _id: 9,
        catName: "Men T-shirt",
        cat_Id: 1,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal9},
            {img:menformal9},
            {img:menformal9},
            {img:menformal9},]
    },
    {
        _id: 10,
        catName: "Men T-shirt",
        cat_Id: 1,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal1},
            {img:menformal1},
            {img:menformal1},
            {img:menformal1},]

    },
    {

        _id: 11,
        catName: "Women's Full Sleeve",
        cat_Id: 2,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "4 THOUGHTS",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women1},
            {img:women1},
            {img:women1},
            {img:women1},
            {img:women1},]
    },
    {
        _id: 12,
        catName: "Women's Full Sleeve",
        cat_Id: 2,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ABSTRACT ELEMENT LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 799,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women2},
            {img:women2},
            {img:women2},
            {img:women2},
            {img:women2},]
    },
    {
        _id: 13,
        catName: "Women's Full Sleeve",
        cat_Id: 2,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ALPHABET PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg:[{img:women3},
            {img:women3},
            {img:women3},
            {img:women3},
            {img:women3},]
    },
    {
        _id: 14,
        catName: "Women's Full Sleeve",
        cat_Id: 2,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BLACK SMOKE OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women4},
            {img:women4},
            {img:women4},
            {img:women4},
            {img:women4},]

    },
    {
        _id: 15,
        catName: "Women's Full Sleeve",
        cat_Id: 2,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BOLD BLACK PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women5},
            {img:women5},
            {img:women5},
            {img:women5},
            {img:women5},]
    },
    {
        _id: 16,
        catName: "Women's Full Sleeve",
        cat_Id: 2,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women6},
            {img:women6},
            {img:women6},
            {img:women6},
            {img:women6},]
    },

    {
        _id: 17,
        catName: "Women's Full Sleeve",
        cat_Id: 2,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women7},
            {img:women7},
            {img:women7},
            {img:women7},
            {img:women7},]
    },

    {
        _id: 18,
        catName: "Women's Full Sleeve",
        cat_Id: 2,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women8},
            {img:women8},
            {img:women8},
            {img:women8},
            {img:women8},]
    },

    {
        _id: 19,
        catName: "Women's Full Sleeve",
        cat_Id: 2,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women9},
            {img:women9},
            {img:women9},
            {img:women9},
            {img:women9},]
    },

    {
        _id: 20,
        catName: "Women's Full Sleeve",
        cat_Id: 2,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg:[{img:women10},
            {img:women10},
            {img:women10},
            {img:women10},
            {img:women10},]
    },
    {

        _id: 21,
        catName: "Women's Half Sleeve",
        cat_Id: 3,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "4 THOUGHTS",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
            magnifyImg: [{img:women1},
                {img:women1},
                {img:women1},
                {img:women1},
                {img:women1},]
    },
    {
        _id: 22,
        catName: "Women's Half Sleeve",
        cat_Id: 3,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ABSTRACT ELEMENT LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 799,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women2},
            {img:women2},
            {img:women2},
            {img:women2},
            {img:women2},]
    },
    {
        _id: 23,
        catName: "Women's Half Sleeve",
        cat_Id: 3,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ALPHABET PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women3},
                     {img:women3},
                     {img:women3},
                     {img:women3},
                     {img:women3},]
    },
    {
        _id: 24,
        catName: "Women's Half Sleeve",
        cat_Id: 3,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BLACK SMOKE OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women4},
            {img:women4},
            {img:women4},
            {img:women4},
            {img:women4},]

    },
    {
        _id: 25,
        catName: "Women's Half Sleeve",
        cat_Id: 3,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BOLD BLACK PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:women5},
                     {img:women5},
                     {img:women5},
                     {img:women5},
                     {img:women5},]
    },
    {
        _id: 26,
        catName: "Women's Half Sleeve",
        cat_Id: 3,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
         magnifyImg: [{img:women6},
                      {img:women6},
                      {img:women6},
                      {img:women6},
                      {img:women7},]
    },

    {
        _id: 27,
        catName: "Women's Half Sleeve",
        cat_Id: 3,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg:
            [{img:women7},
            {img:women7},
            {img:women7},
            {img:women7},
            {img:women7},]
    },

    {
        _id: 28,
        catName: "Women's Half Sleeve",
        cat_Id: 3,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:women8},
            {img:women8},
            {img:women8},
            {img:women8},
            {img:women8},]
    },
    {
        _id: 29,
        catName: "Women's Half Sleeve",
        cat_Id: 3,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg:
            [{img:women9},
            {img:women9},
            {img:women9},
            {img:women9},
            {img:women9},]
    },
    {
        _id: 30,
        catName: "Women's Half Sleeve",
        cat_Id: 3,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:women10},
            {img:women10},
            {img:women10},
            {img:women10},
            {img:women10},]  
    },

    {


        _id: 31,
        catName: "Couple Shirts",
        cat_Id: 4,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "4 THOUGHTS",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
            [{img:cup1},
            {img:cup1},
            {img:cup1},
            {img:cup1},]

    },
    {
        _id: 32,
        catName: "Couple Shirts",
        cat_Id: 4,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ABSTRACT ELEMENT LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 799,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:cup2},
            {img:cup2},
            {img:cup2},
            {img:cup2},]
    },
    {
        _id: 33,
        catName: "Couple Shirts",
        cat_Id: 4,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ALPHABET PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:cup3},
            {img:cup3},
            {img:cup3},
            {img:cup3},]
    },
    {
        _id: 34,
        catName: "Couple Shirts",
        cat_Id: 4,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BLACK SMOKE OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:cup4},
            {img:cup4},
            {img:cup4},
            {img:cup4},]
    },
    {
        _id: 35,
        catName: "Couple Shirts",
        cat_Id: 4,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BOLD BLACK PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
            [{img:cup5},
            {img:cup5},
            {img:cup5},
            {img:cup5},]
    },
    {
        _id: 36,
        catName: "Couple Shirts",
        cat_Id: 4,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
        
           [{img:cup6},
            {img:cup6},
            {img:cup6},
            {img:cup6},]
    },

    {
        _id: 37,
        catName: "Couple Shirts",
        cat_Id: 4,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:cup7},
            {img:cup7},
            {img:cup7},
            {img:cup7},]
    },

    {
        _id: 38,
        catName: "Couple Shirts",
        cat_Id: 4,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:cup8},
            {img:cup8},
            {img:cup8},
            {img:cup8},]
    },

    {
        _id: 39,
        catName: "Couple Shirts",
        cat_Id: 4,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:cup9},
            {img:cup9},
            {img:cup9},
            {img:cup9},]
    },
    {
        _id: 68,
        catName: "Couple Shirts",
        cat_Id: 4,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:cup10},
            {img:cup10},
            {img:cup10},
            {img:cup10},]
    },

    {

        _id: 40,
        catName: "Formal Shirts",
        cat_Id: 5,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "4 THOUGHTS",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:men1},
            {img:men1},
            {img:men1},
            {img:men1},]
    },
    {

        _id: 41,
        catName: "Formal Shirts",
        cat_Id: 5,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ABSTRACT ELEMENT LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 799,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:men2},
            {img:men2},
            {img:men2},
            {img:men2},]
    },
    {
        _id: 42,
        catName: "Formal Shirts",
        cat_Id: 5,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ALPHABET PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:men3},
            {img:men3},
            {img:men3},
            {img:men3},]
    },
    {
        _id: 43,
        catName: "Formal Shirts",
        cat_Id: 5,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BLACK SMOKE OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:men4},
            {img:men4},
            {img:men4},
            {img:men4},]
    },
    {
        _id: 44,
        catName: "Formal Shirts",
        cat_Id: 5,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BOLD BLACK PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:men1},
            {img:men1},
            {img:men1},
            {img:men1},]
    },
    {
        _id: 45,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg:
           [{img:men2},
            {img:men2},
            {img:men2},
            {img:men2},]
    },


    {
        _id: 46,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "FORMAL SHIRTS",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: false,
        magnifyImg:[{img:men1},
            {img:men1},
            {img:men1},
            {img:men1},]
    },
    {
        _id: 47,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "Half Sleeve's",
        catName: "Men's/Women's",
        cat_Id: 6,
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:MW2},
            {img:MW2},
            {img:MW2},
            {img:MW2},]
    },
    {
        _id: 48,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "Men's Tshirt",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal1},
            {img:menformal1},
            {img:menformal1},
            {img:menformal1},]

    },
    {
        _id: 49,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "Men's Half Sleeves",
        catName: "Men's/Women's",
        cat_Id: 6,
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal1},
            {img:menformal1},
            {img:menformal1},
            {img:menformal1},]

    },
    {
        _id: 50,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "COUPLE SHIRTS",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal1},
            {img:menformal1},
            {img:menformal1},
            {img:menformal1},]

    },
    {
        _id: 51,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "WOMEN,S FULL SLEEVE",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal1},
            {img:menformal1},
            {img:menformal1},
            {img:menformal1},]
    },
    {

        _id: 52,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "4 THOUGHTS",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal1},
            {img:menformal1},
            {img:menformal1},
            {img:menformal1},]
    },
    {
        _id: 53,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ABSTRACT ELEMENT LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 799,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal2},
            {img:menformal2},
            {img:menformal2},
            {img:menformal2},]
    },
    {
        _id: 54,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ALPHABET PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal3},
            {img:menformal3},
            {img:menformal3},
            {img:menformal3},]
    },
    {
        _id: 55,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BLACK SMOKE OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal4},
            {img:menformal4},
            {img:menformal4},
            {img:menformal4},]
    },
    {
        _id: 56,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BOLD BLACK PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal5},
            {img:menformal5},
            {img:menformal5},
            {img:menformal5},]
    },
    {
        _id: 57,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal6},
            {img:menformal6},
            {img:menformal6},
            {img:menformal6},]
    },
    {
        _id: 58,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal7},
            {img:menformal7},
            {img:menformal7},
            {img:menformal7},]
    },
    {
        _id: 59,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal8},
            {img:menformal8},
            {img:menformal8},
            {img:menformal8},]

    },

    {
        _id: 60,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal9},
            {img:menformal9},
            {img:menformal9},
            {img:menformal9},]
    },

    {
        _id: 61,
        catName: "Men's/Women's",
        cat_Id: 6,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal1},
            {img:menformal1},
            {img:menformal1},
            {img:menformal1},]

    },
    {
        _id: 62,
        catName: "Men's Half Sleeve",
        cat_Id: 7,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "4 THOUGHTS",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal1},
            {img:menformal1},
            {img:menformal1},
            {img:menformal1},]
    },
    {

        _id: 63,
        catName: "Men's Half Sleeve",
        cat_Id: 7,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ABSTRACT ELEMENT LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 799,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg:[{img:menformal2},
            {img:menformal2},
            {img:menformal2},
            {img:menformal2},]
    },
    {
        _id: 64,
        catName: "Men's Half Sleeve",
        cat_Id: 7,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ALPHABET PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal3},
            {img:menformal3},
            {img:menformal3},
            {img:menformal3},]
    },
    {
        _id: 65,
        catName: "Men's Half Sleeve",
        cat_Id: 7,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BLACK SMOKE OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg:  [{img:menformal4},
            {img:menformal4},
            {img:menformal4},
            {img:menformal4},]
    },
    {
        _id: 66,
        catName: "Men's Half Sleeve",
        cat_Id: 7,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BOLD BLACK PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:menformal1},
            {img:menformal1},
            {img:menformal1},
            {img:menformal1},]
    },
    {
        _id: 67,
        catName: "Men's Half Sleeve",
        cat_Id: 7,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BANDANA LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg:[{img:menformal2},
            {img:menformal2},
            {img:menformal2},
            {img:menformal2},]
    },

    {
        _id: 68,
        catName: "Men's Full Sleeve",
         cat_Id: 9,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "4 THOUGHTS",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:men1},
            {img:men1},
            {img:men1},
            {img:men1},]
    },
    {

        _id: 69,
        catName: "Men's Full Sleeve",
         cat_Id: 9,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ABSTRACT ELEMENT LOW SHOULDER SHIRT",
        orgPrice: 1199.00,
        discPrice: 799,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:men2},
            {img:men2},
            {img:men2},
            {img:men2},]
    },
    {
        _id: 70,
        catName: "Men's Full Sleeve",
         cat_Id: 9,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ALPHABET PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:men3},
            {img:men3},
            {img:men3},
            {img:men3},]
    },
    {
        _id: 71,
        catName: "Men's Full Sleeve",
         cat_Id: 9,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BLACK SMOKE OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:men4},
            {img:men4},
            {img:men4},
            {img:men4},]
    },
    {
        _id: 72,
        catName: "Men's Full Sleeve",
         cat_Id: 9,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "BOLD BLACK PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: [{img:men1},
            {img:men1},
            {img:men1},
            {img:men1},]
    },
    {
        _id: 71,
        catName: "Men's Full Sleeve",
         cat_Id: 9,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "ALPHABET PRINTED OVERSIZED SHIRT MEN",
        orgPrice: 1199.00,
        discPrice: 849,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:men3},
            {img:men3},
            {img:men3},
            {img:men3},]
    },
    {
        _id: 68,
        catName: "Men's Full Sleeve",
         cat_Id: 9,
        isAvailable: true,
        titDesc: [{ title: "hello this is title", description: "hello this is description" }],
        productName: "4 THOUGHTS",
        orgPrice: 1199.00,
        discPrice: 649,
        sale: true,
        productQty: 33,
        isCatAvailable: true,
         sizeChart: { small: true, medium: true, large: true, extraLarge: true, XXL: true },
        sizeImage: "",
        magnifyImg: 
           [{img:men1},
            {img:men1},
            {img:men1},
            {img:men1},]
    },
   
]
export default AllCat;





