import mongoose from "mongoose";

const favItemSchema = new mongoose.Schema({
    itemName:{
        type:String,
        required:true
    },
    isAvailable:{
        type:Boolean,
        required:false,
        default:false
    },
    description:{
        type:String,
        required:true
    },
    ingridients:[
        {name:{
            type:String,
            required:true
        }},
        {name:{
            type:String,
            required:true
        }},
        {name:{
            type:String,
            required:true
        }},
        {name:{
            type:String,
            required:true
        }}
    ],
    size:[
        {
            small:{
                mrp:{
                    type:Number,
                    required:true
                },
                srp:{
                    type:Number,
                    required:true
                },
                isStock:{
                    type:Boolean,
                    required:false,
                    default:false
                }
            },
            medium:{
                mrp:{
                    type:Number,
                    required:true
                },
                srp:{
                    type:Number,
                    required:true
                },
                isStock:{
                    type:Boolean,
                    required:false,
                    default:false
                }
            },
            large:{
                mrp:{
                    type:Number,
                    required:true
                },
                srp:{
                    type:Number,
                    required:true
                },
                isStock:{
                    type:Boolean,
                    required:false,
                    default:false
                }
            }
        }
    ],
    isPopular:{
        type:Boolean,
        required:false,
        default:false
    }
},{timestamps:true});

export default favItemSchema