import VibzContext from '@/Global/VibzContext'
import FloatingButtons from '@/components/FloatingButtons'


export const metadata = {
  title: 'The Vibzz',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{margin:"0px",padding:"0px"}}>
      <VibzContext>
               {children}
      </VibzContext>
      <FloatingButtons/>
      
      </body>
    </html>
  )
}
